sudo: false
dist: xenial

matrix:
  include:

  - os: linux
    addons:
      apt:
        packages:
          - build-essential
          - libglu1-mesa-dev
          - libpulse-dev
          - libglib2.0-dev
          - libdbusmenu-qt5-dev
          - libqt*5-dev
          - qt*5-dev
    env:
    - LABEL="linux"

script:
- export NibbleClassic_URL=https://api.github.com/repos/NibbleClassic/NibbleClassic/releases/latest

# Linux build commands
- if [[ "$LABEL" == "linux" ]]; then ./scripts/build_linux.sh ; fi
- if [[ "$LABEL" == "linux" ]]; then rm -rf *.tar.gz ; fi
- if [[ "$LABEL" == "linux" ]]; then export LATEST_NibbleClassic=`curl -s $NibbleClassic_URL | grep browser_download_url | grep linux | cut -d '"' -f 4 | cut -d '/' -f 9` ; fi
- if [[ "$LABEL" == "linux" ]]; then export NibbleClassic_DOWNLOAD=`curl -s $NibbleClassic_URL | grep browser_download_url | grep linux | cut -d '"' -f 4` ; fi
- if [[ "$LABEL" == "linux" ]]; then wget $NibbleClassic_DOWNLOAD ; fi
- if [[ "$LABEL" == "linux" ]]; then tar xzf $LATEST_NibbleClassic --strip-components 1 ; fi
- if [[ "$LABEL" == "linux" ]]; then cp NibbleClassicd turtle-service ./deploy/linux ; fi
- if [[ "$LABEL" == "linux" ]]; then ls -la ./deploy/linux ; fi

- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- rm -rf NibbleClassic-Nest-${TRAVIS_TAG}
- mkdir NibbleClassic-Nest-${TRAVIS_TAG}
- cp LICENSE.md NibbleClassic-Nest-${TRAVIS_TAG}
- /bin/cp -r ./deploy/${LABEL}/* ./NibbleClassic-Nest-${TRAVIS_TAG}
- tar cvfz NibbleClassic-Nest-${TRAVIS_TAG}-${LABEL}.tar.gz NibbleClassic-Nest-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp NibbleClassic-Nest-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- ls -la ./builds

